<?php
/*
  $Id$

  generated by: 
  https://oscompose.com (c)2018

  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com

  Copyright (c) 2018 osCommerce

  Released under the GNU General Public License
*/


  define('MODULE_CAROUSEL_ROTATOR_TITLE', 'Carousel Banners For Index Page');
  define('MODULE_CAROUSEL_ROTATOR_DESCRIPTION', 'Adds a carousel to Index Page with banner images set from Banner Manager.');
  
  
?>
