<?php
/*
  $Id$

  generated by:
  https://oscompose.com (c)2018, Pureosc.com (c) 2024

  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com

  Copyright (c) 2024 osCommerce

  Released under the GNU General Public License
 */
?>
<style>
.banner {padding-top:20px}
.banner img{width:100%;height:auto}
<?php
if ($counter === 1) {
    echo '.banner a:nth-of-type(1){width:100%;left:0}';
}

if ($counter === 2) {
    echo <<<'EOD'

.banner a:nth-of-type(1){width:50%;left:0%;}
.banner a:nth-of-type(2){width:50%;left:50%;}
EOD;
}

if ($counter === 3) {
    echo <<<'EOD'
.banner a:nth-of-type(1){width:33%;left:0%;}
.banner a:nth-of-type(2){width:33%;left:33%;}
.banner a:nth-of-type(3){width:33%;left:66%;}
EOD;
}

?>
</style><!--TODO:css -->
   <div class="banner">
<?php
echo tep_image('images/rotator.webp');
echo $carousel; ?>
</div>




